# Standards: 0.11
---

# 1.1.3 Ensure nodev option set on /tmp partition

- name: 1.1.3 - Ensure nodev option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored
