# Standards: 0.11
---

# 1.1.1.7 - Ensure mounting of udf filesystems is disabled

- name: 1.1.1.7 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_7
  tags:
    - level-1
    - section-1
    - "1.1.1.7"
    - scored

- name: 1.1.1.7 - Ensure mounting of udf filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install udf /bin/true\n"
  when: modprobe_1_1_1_7.stat.exists is not defined or not modprobe_1_1_1_7.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.7"
    - scored

- name: 1.1.1.7 - Ensure mounting of udf filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install udf"
    line: "install udf /bin/true"
  when: modprobe_1_1_1_7.stat.exists is defined and modprobe_1_1_1_7.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.7"
    - scored

