# Standards: 0.11
---

# 1.1.1.2 - Ensure mounting of freevxfs filesystems is disabled

- name: 1.1.1.2 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_2
  tags:
    - level-1
    - section-1
    - "1.1.1.2"
    - scored

- name: 1.1.1.2 - Ensure mounting of freevxfs filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install freevxfs /bin/true\n"
  when: modprobe_1_1_1_2.stat.exists is not defined or not modprobe_1_1_1_2.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.2"
    - scored

- name: 1.1.1.2 - Ensure mounting of freevxfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install freevxfs"
    line: "install freevxfs /bin/true"
  when: modprobe_1_1_1_2.stat.exists is defined and modprobe_1_1_1_2.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.2"
    - scored

