# Standards: 0.11
---

# 1.1.14 Ensure nodev option set on /home partition

- name: 1.1.14 - Ensure nodev option set on /home partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/home'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.14"
    - scored
