# Standards: 0.11
---

# 1.1.19 - Disable Automounting

- name: 1.1.19 - Disable autofs
  service:
    name: autofs
    enabled: false
    state: stopped
  register: autofs_result
#  failed_when: "autofs_result.failed and 'no service or tool found for: autofs' not in autofs_result.msg"
  failed_when: "autofs_result.failed and 'Could not find the requested service' not in autofs_result.msg"
  tags:
    - level-1
    - "1.1.19"
    - scored
