# Standards: 0.11
---

# 1.4.1 Ensure permissions on bootloader config are configured

- name: 1.4.1 - Check if grub bootloader file exists
  stat:
    path: "{{ cis_grub_bootloader_filename }}"
  register: grub_1_4_1
  tags:
    - level-1
    - "1.4.1"
    - scored

- name: 1.4.1 - Set permissions on grub configuration
  file:
    path: "{{ cis_grub_bootloader_filename }}"
    owner: root
    group: root
    mode:  "og-rwx"
    state: file
  when: grub_1_4_1.stat.exists
  tags:
    - level-1
    - "1.4.1"
    - scored
