# Standards: 0.11
---

# 2.1.3 Ensure discard services are not enabled

- name: 2.1.3 - Ensure discard services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: "{{ cis_discard_state }}"
  with_items:
    - discard-dgram
    - discard-stream
  when:  cis_xinetd_state != 'absent'
  tags:
    - level-1
    - section-2
    - "2.1.3"
    - scored
