# Standards: 0.11
---

# 2.1.8 Ensure telnet server is not enabled

- name: 2.1.8 - Ensure telnet server is {{ cis_telnet_install.state }}
  yum:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ cis_telnet_install }}"
  tags:
    - level-1
    - section-2
    - "2.1.8"
    - scored

- name: 2.1.8 - If telnet server is installed set appropriate service - {{ cis_telnet_install.exception }}
  service:
    name: "{{ item.service }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.rstate }}"
  when: cis_telnet_install.state == 'present'
  with_items:
    - "{{ cis_telnet_install }}"
  tags:
    - level-1
    - section-2
    - "2.1.8"
    - scored
