# Standards: 0.11
---

# 2.1.10 Ensure rsync server is not enabled

- name: 2.1.10 - Ensure rsync server is {{ cis_rsync_install.state }}
  yum:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ cis_rsync_install }}"
  tags:
    - level-1
    - section-2
    - "2.1.10"
    - scored

- name: 2.1.10 - If rsync server is installed set appropriate service - {{ cis_rsync_install.exception }}
  service:
    name: "{{ item.service }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.rstate }}"
  when: cis_rsync_install.state == 'present'
  with_items:
    - "{{ cis_rsync_install }}"
  tags:
    - level-1
    - section-2
    - "2.1.10"
    - scored

