# Standards: 1.1.24 
---

# 2.2.1.2 Ensure ntp is configured

- name: Install NTP configuration
  template:
    src: templates/ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root
    backup: true
  notify: Restart ntpd
  when: cis_enable_ntp and not cis_enable_chrony
  tags:
    - level-1
    - section-4
    - "2.2.1.2"
    - not-scored
