# Standards: 0.11
---

# 2.2.10 Ensure HTTP services is not enabled

- name: 2.2.10 - Ensure HTTP services are correct, to many varities to list
  yum:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ cis_httpd_install }}"
    - "{{ cis_apache_install }}"
    - "{{ cis_apache2_install }}"
    - "{{ cis_nginx_install }}"
    - "{{ cis_lighttpd_install }}"
  tags:
    - level-1
    - "2.2.10"
    - scored

- name: 2.2.10 - Ensure HTTP Service is correct, to many varities to list
  service:
    name: "{{ item.service }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.rstate }}"
  with_items:
    - "{{ cis_httpd_install }}"
    - "{{ cis_apache_install }}"
    - "{{ cis_apache2_install }}"
    - "{{ cis_nginx_install }}"
    - "{{ cis_lighttpd_install }}"
  when: item.state == "present"
  tags:
    - level-1
    - "2.2.10"
    - scored
