# Standards: 0.11
---

# 2.2.1.3 Ensure chrony is configured

- name: Install chrony configuration
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
  notify: Restart chronyd
  when: cis_enable_chrony and not cis_enable_ntp
  tags:
    - level-1
    - section-4
    - "2.2.1.3"
    - not-scored
