# Standards: 0.11
---

# 3.6.4 Ensure outbound and established connections are configured

- name: 3.6.4 - Ensure outbound and established connections are configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-3
    - "3.6.4"
    - not-scored
