# Standards: 0.11
---

# 3.6.2 Ensure default deny firewall policy

- name: 3.6.2 - Ensure default deny firewall policy
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored
