# Standards: 1.1.5
---

# 4.2.1.1 Ensure rsyslog Service is enabled

- name: 4.2.1.1 - Check if rsyslog is installed
  yum:
    name: rsyslog
    state: present
  when: cis_enable_rsyslog
#  register: rsyslog_4_2_1_1
  tags:
    - level-1
    - section-4
    - "4.2.1.1"
    - scored
    - skip_ansible_lint

- name: 4.2.1.1 - Ensure rsyslog Service is enabled
  service:
    name: "rsyslog"
    enabled: true
    state: started
  when:
    - cis_enable_rsyslog
#    - rsyslog_4_2_1_1.rc is not defined or rsyslog_4_2_1_1.rc == 0
  ignore_errors: false
  tags:
    - level-1
    - section-4
    - "4.2.1.1"
    - scored
