# Standards: 0.11
---

# 4.2.2.3 Ensure syslog-ng default file permissions configured

- name: 4.2.2.3 - Ensure syslog-ng default file permissions configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-4
    - "4.2.2.3"
    - scored
    - todo
