# Standards: 1.1.25 
---

# 4.3 - Ensure logrotate is configured

- name: Install logrotate configuration
  template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.conf
    mode: 0644
    owner: root
    group: root
    backup: true
  tags:
    - level-1
    - section-4
    - "2.2.1.2"
    - not-scored
