# Standards: 0.11
---

# 5.2.3 - Ensure SSH LogLevel is set to INFO

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored

- name: 5.2.3 - Ensure SSH LogLevel is set to INFO
  lineinfile:
    regexp: "^LogLevel\\s+"
    line: "LogLevel INFO"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
