# Standards: 0.11
---

# 5.2.8 - Ensure SSH root login is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.8"
    - scored

- name: 5.2.8 - Ensure SSH root login is disabled
  lineinfile:
    regexp: "^PermitRootLogin\\s+"
    line: "PermitRootLogin no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.8"
    - scored
