# Standards: 0.11
---

# 5.2.7 - Ensure SSH HostbasedAuthentication is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.7"
    - scored

- name: 5.2.7 - Ensure SSH HostbasedAuthentication is disabled
  lineinfile:
    regexp: "^HostbasedAuthentication\\s+"
    line: "HostbasedAuthentication no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.7"
    - scored
