# Standards: 0.11
---

# 5.3.3 Ensure password reuse is limited

- name: 5.3.3 - Ensure password reuse is limited
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored
    - todo
