# Standards: 0.11
---

# 6.1.4 Ensure permissions on /etc/group are configured

- name: 6.1.4 - Ensure permissions on /etc/group are configured
  file:
    path: /etc/group
    owner: root
    group: root
    mode: 0644
  tags:
    - level-1
    - section-6
    - "6.1.4"
    - scored
