# Standards: 0.11
---

# 6.2.6 Ensure root PATH Integrity

- name: 6.2.6 - Audit root PATH Integrity
  script: "{{ role_path }}/files/audit_6.2.6.sh"
  check_mode: no
  changed_when: False
  register: audit_6_2_6
  tags:
    - level-1
    - section-6
    - "6.2.6"
    - scored

- name: 6.2.6 - Ensure root PATH Integrity
  fail:
    msg: "{{ audit_6_2_6.stdout_lines }}"
  when:
    - audit_6_2_6.stdout_lines is defined and audit_6_2_6.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.6"
    - scored

- name: 6.2.6 - Ensure root PATH Integrity
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_2_6.stdout }}"
  when:
    - audit_6_2_6.stdout_lines is defined and audit_6_2_6.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.6"
    - scored

